apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-worker
  namespace: llm
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: vllm-worker=ghcr.io/johnny-dai-git/llm-deployment/vllm-worker
    argocd-image-updater.argoproj.io/vllm-worker.update-strategy: name
    argocd-image-updater.argoproj.io/vllm-worker.allow-tags: regexp:^v-[0-9]{8}-[0-9]{6}$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-credentials
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-worker
  template:
    metadata:
      labels:
        app: llm-worker
    spec:
      nodeSelector:
        gpu-node: "true"
      containers:
      - name: llm-worker
        image: ghcr.io/johnny-dai-git/llm-deployment/vllm-worker:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        resources:
          limits:
            nvidia.com/gpu: 1

