apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-gateway
  namespace: llm
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: gateway=ghcr.io/johnny-dai-git/llm-deployment/gateway
    argocd-image-updater.argoproj.io/gateway.update-strategy: semver
    argocd-image-updater.argoproj.io/gateway.allow-tags: regexp:^v?[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-gateway
  template:
    metadata:
      labels:
        app: llm-gateway
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        system: "true"
      containers:
      - name: llm-gateway
        image: ghcr.io/johnny-dai-git/llm-deployment/gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: ROUTER_URL
          value: "http://llm-router.llm.svc.cluster.local:8001"

