apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-router
  namespace: llm
  annotations:
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: router=ghcr.io/johnny-dai-git/llm-deployment/router
    argocd-image-updater.argoproj.io/router.update-strategy: name
    argocd-image-updater.argoproj.io/router.allow-tags: regexp:^v-[0-9]{8}-[0-9]{6}$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-credentials
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-router
  template:
    metadata:
      labels:
        app: llm-router
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        system: "true"
      containers:
      - name: llm-router
        image: ghcr.io/johnny-dai-git/llm-deployment/router:latest
        ports:
        - containerPort: 8001
        env:
        - name: WORKER_LIST
          value: "llm-worker.llm.svc.cluster.local:8002"

